## load dataset

In [48]:
from mxnet import nd
import random
import zipfile

In [49]:
with zipfile.ZipFile('../data/jaychou_lyrics.txt.zip') as zin:
    with zin.open('jaychou_lyrics.txt') as f:
        corpus_chars=f.read().decode('utf-8')
corpus_chars=corpus_chars.replace('\n',' ').replace('\t',' ')
corpus_chars=corpus_chars[:10000]

## 索引

In [50]:
idx_to_char=list(set(corpus_chars))
char_to_idx=dict([[char ,idx] for idx,char in enumerate(idx_to_char)])
vocal_size=len(char_to_idx)
corpus_idxs=[char_to_idx[char] for char in corpus_chars]

## 采样

In [51]:
import numpy as np
def data_iter_random(corpus_idxs,batch_size,num_step):
    num_sample=(len(corpus_idxs)-1)//num_step
    train_features=np.array(corpus_idxs[:num_sample*num_step]).reshape(num_sample,num_step)
    train_labels=np.array(corpus_idxs[1:num_sample*num_step+1]).reshape(num_sample,num_step)
    for i in range(num_sample//batch_size):
        pos=i*batch_size
        X=train_features[pos:pos+batch_size,:]
        Y=train_labels[pos:pos+batch_size,:]
        yield nd.array(X),nd.array(Y)

In [52]:
my_seq=list(range(30))
for X,Y in data_iter_random(my_seq,batch_size=2,num_step=6):
    print(X)
    print(Y)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
<NDArray 2x6 @cpu(0)>

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]
<NDArray 2x6 @cpu(0)>

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
<NDArray 2x6 @cpu(0)>

[[13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]]
<NDArray 2x6 @cpu(0)>
