In [2]:
from mxnet import gluon,nd
from mxnet.gluon import nn

In [6]:
class CenteredLayer(nn.Block):
    def __init___(self):
        super(CenteredLayer,self).__init__()
        
    def forward(self,X):
        return X-X.mean()

In [8]:
layer=CenteredLayer()
layer(nd.array([1,2,3,4,5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [25]:
net=nn.Sequential()
net.add(nn.Dense(128),
       CenteredLayer())
net.initialize()
y=net(nd.random.uniform(shape=(4,8)))
y.mean().asscalar()

8.731149e-11

In [28]:

class MyDense(nn.Block):
    def __init__(self,units,in_units):
        super(MyDense,self).__init__()
        self.weight=self.params.get('weight',shape=(in_units,units))
        self.bias=self.params.get('bias',shape=(units,))
    def forward(self,X):
        linear=nd.dot(X,self.weight.data())+self.bias.data()
        return nd.relu(linear)

In [33]:
dense=MyDense(units=5,in_units=10)
dense.params

mydense4_ (
  Parameter mydense4_weight (shape=(10, 5), dtype=<class 'numpy.float32'>)
  Parameter mydense4_bias (shape=(5,), dtype=<class 'numpy.float32'>)
)

In [74]:
dense.initialize(force_reinit=True)

dense(nd.random.uniform(shape=(2,10)))


[[0.06270994 0.         0.         0.03540236 0.05771798]
 [0.11660068 0.         0.         0.00395355 0.07381044]]
<NDArray 2x5 @cpu(0)>

In [71]:
net=nn.Sequential()
net.add(MyDense(32,64),
       MyDense(2,32))
net.initialize()
net(nd.random.uniform(shape=(2,64)))


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>